"""Generate ECDSA P-384 test vectors with OpenSSL.

The point is that the signatures are not ours. Our verifier is hand-written, and
a hand-written verifier checked only against signatures it also produced proves
nothing: both halves could share one misunderstanding. Here OpenSSL signs, we
verify, and we have to agree on the rejections too.

Run when the vectors need regenerating:
    python3 crates/trailryx-verify/tests/make_vectors.py > crates/trailryx-verify/tests/p384_vectors.txt
"""

import hashlib
import subprocess
import sys
import tempfile
from pathlib import Path

CASES = 12


def run(args, stdin=None):
    return subprocess.run(args, input=stdin, capture_output=True, check=True).stdout


def der_to_raw(der: bytes) -> bytes:
    """SEQUENCE { INTEGER r, INTEGER s } to a fixed 96 bytes."""
    assert der[0] == 0x30
    body = der[2:] if der[1] < 0x80 else der[2 + (der[1] & 0x7F):]
    out = b""
    at = 0
    for _ in range(2):
        assert body[at] == 0x02
        length = body[at + 1]
        value = body[at + 2 : at + 2 + length]
        at += 2 + length
        value = value.lstrip(b"\x00")
        out += value.rjust(48, b"\x00")
    return out


def main() -> int:
    print("# public_key_hex message_hex signature_hex expect_valid")
    print("# generated by openssl:", run(["openssl", "version"]).decode().strip())
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        for case in range(CASES):
            key = tmp / "k.pem"
            run(["openssl", "ecparam", "-name", "secp384r1", "-genkey", "-noout", "-out", str(key)])
            spki = run(["openssl", "ec", "-in", str(key), "-pubout", "-outform", "DER"])
            public = spki[-97:]
            assert public[0] == 0x04

            message = hashlib.sha256(f"trailryx vector {case}".encode()).digest() * (case % 3 + 1)
            msg_path = tmp / "m.bin"
            msg_path.write_bytes(message)
            der = run(["openssl", "dgst", "-sha384", "-sign", str(key), str(msg_path)])
            raw = der_to_raw(der)

            print(f"{public.hex()} {message.hex()} {raw.hex()} 1")

            # The same signature against a message one bit different.
            other = bytearray(message)
            other[0] ^= 1
            print(f"{public.hex()} {bytes(other).hex()} {raw.hex()} 0")

            # A signature one bit different against the right message.
            broken = bytearray(raw)
            broken[case * 7 % 96] ^= 1
            print(f"{public.hex()} {message.hex()} {bytes(broken).hex()} 0")

            # The right signature under somebody else's key.
            other_key = tmp / "k2.pem"
            run(["openssl", "ecparam", "-name", "secp384r1", "-genkey", "-noout", "-out", str(other_key)])
            other_spki = run(["openssl", "ec", "-in", str(other_key), "-pubout", "-outform", "DER"])
            print(f"{other_spki[-97:].hex()} {message.hex()} {raw.hex()} 0")
    return 0


if __name__ == "__main__":
    sys.exit(main())
