#!/usr/bin/env python3
"""Write the conformance corpus to stdout as TSV: name, hex, verdict.

The bytes are hex-encoded because a corpus stored as text loses exactly the
cases that matter. Invalid UTF-8 cannot round-trip through a text file at all, a
NUL byte is dropped or truncated by half the tools that would touch the file,
and a byte-order mark is silently eaten by editors. Hex survives all three, and
it also survives being pasted into a bug report.

`verdict` is what RFC 8259 requires of any parser, not what trailryx does:

    y   a conforming parser must accept these bytes
    n   a conforming parser must reject these bytes
    i   the grammar is satisfied but the answer is implementation-defined,
        because a bound, a numeric range or a lone surrogate is involved

Case names follow the JSONTestSuite convention (prefix `y_`, `n_` or `i_`
matching the verdict, then a descriptive tail) so a name can be compared against
the upstream corpus by eye. What trailryx is expected to do with each case lives
in EXPECTATIONS.tsv, deliberately in a separate file: the RFC verdict and our
verdict are different claims and merging them would hide the three places we
knowingly diverge.

Every case here is hand-written from a named divergence class in "Parsing JSON
is a Minefield". Nothing is generated by fuzzing: a fuzzer finds bytes nobody
can explain, and a corpus whose cases nobody can explain stops being maintained.
"""

import sys

# One entry per case. Built as a list rather than a dict so the file reads in
# class order and so a duplicated name is caught by the check at the bottom
# instead of silently replacing its twin and shrinking the corpus.
CASES: list[tuple[str, bytes, str]] = []


def case(name: str, raw: bytes, verdict: str) -> None:
    CASES.append((name, raw, verdict))


def nested_arrays(n: int) -> bytes:
    """`n` arrays, properly closed."""
    return b"[" * n + b"]" * n


def object_of(n: int) -> bytes:
    """One object with `n` distinct members, to sit either side of a bound."""
    members = b",".join(b'"k%d":%d' % (i, i) for i in range(n))
    return b"{" + members + b"}"


def digits(n: int) -> bytes:
    """An integer literal of exactly `n` digits, no leading zero."""
    return b"1" + b"0" * (n - 1)


# --------------------------------------------------------------------------
# Structure. Unclosed containers, separators in the wrong place, and more than
# one value where one is allowed.
#
# The two-values class is the one with teeth. A parser that reads the first
# value and stops has no way to report the second, so a synthetic audit record
# appended to a legitimate one becomes invisible rather than fatal.
# --------------------------------------------------------------------------
case("y_structure_lonely_true", b"true", "y")
case("y_structure_lonely_false", b"false", "y")
case("y_structure_lonely_null", b"null", "y")
case("y_structure_lonely_int", b"42", "y")
case("y_structure_lonely_negative_real", b"-0.1", "y")
case("y_structure_lonely_string", b'"asd"', "y")
case("y_structure_empty_array", b"[]", "y")
case("y_structure_empty_object", b"{}", "y")
case("y_structure_array_of_one_object", b'[{"a":1}]', "y")
case("y_structure_object_of_one_array", b'{"a":[1,2,3]}', "y")
case("y_structure_object_of_object_of_array", b'{"a":{"b":[1,{"c":null}]}}', "y")
case("y_structure_array_of_every_scalar", b'[null,true,false,0,"s"]', "y")
case("y_structure_nested_25_deep", nested_arrays(25), "y")
case("y_structure_array_1000_elements", b"[" + b",".join([b"1"] * 1000) + b"]", "y")
case("y_structure_object_256_members", object_of(256), "y")

# Depth and member count are bounds, so the answer is the implementation's.
case("i_structure_nested_26_deep", nested_arrays(26), "i")
# The container bound is a backstop rather than a derived parity device, so a
# case at it and a case past it both track whatever it currently is. 33 is one
# past the default of 32; the bound itself is exercised by the dedicated test
# in corpus.rs, which reads it from Limits::default().
case("i_structure_nested_33_deep", nested_arrays(33), "i")
case("i_structure_nested_1000_deep", nested_arrays(1000), "i")
case("i_structure_nested_100000_deep", nested_arrays(100000), "i")
case("i_structure_object_257_members", object_of(257), "i")

# A hundred thousand opening brackets is not a depth question first. It is
# unclosed, so the grammar already refuses it; the point of the case is that a
# recursive parser dies on it with a stack overflow rather than an error.
case("n_structure_100000_opening_brackets", b"[" * 100000, "n")
case("n_structure_alternating_nesting_unclosed", b'[{"":' * 50, "n")
case("n_structure_open_array", b"[", "n")
case("n_structure_open_object", b"{", "n")
case("n_structure_open_object_after_name", b'{"a"', "n")
case("n_structure_open_object_after_colon", b'{"a":', "n")
case("n_structure_open_array_after_value", b"[1", "n")
case("n_structure_open_array_nested", b"[[1]", "n")
case("n_structure_close_unopened_array", b"]", "n")
case("n_structure_close_unopened_object", b"}", "n")
case("n_structure_mismatched_brackets", b"[1}", "n")
case("n_structure_array_trailing_comma", b"[1,]", "n")
case("n_structure_object_trailing_comma", b'{"a":1,}', "n")
case("n_structure_array_double_comma", b"[1,,2]", "n")
case("n_structure_array_comma_only", b"[,]", "n")
case("n_structure_array_leading_comma", b"[,1]", "n")
case("n_structure_object_leading_comma", b'{,"a":1}', "n")
case("n_structure_object_comma_where_value_belongs", b'{"a":,}', "n")
case("n_structure_object_missing_colon", b'{"a" 1}', "n")
case("n_structure_object_double_colon", b'{"a"::1}', "n")
case("n_structure_object_comma_for_colon", b'{"a",1}', "n")
case("n_structure_object_colon_before_name", b'{:"a"}', "n")
case("n_structure_object_number_key", b"{1:2}", "n")
case("n_structure_object_unquoted_key", b"{a:1}", "n")
case("n_structure_object_extra_content", b"{}{}", "n")
case("n_structure_two_bare_values", b"1 2", "n")
case("n_structure_two_objects_one_line", b'{"a":1} {"b":2}', "n")
case("n_structure_two_arrays_no_space", b"[][]", "n")
case("n_structure_trailing_nul", b'{"a":1}\x00', "n")
case("n_structure_leading_nul", b'\x00{"a":1}', "n")
case("n_structure_empty_document", b"", "n")
case("n_structure_only_whitespace", b"   ", "n")
case("n_structure_single_comma", b",", "n")
case("n_structure_single_colon", b":", "n")
case("n_structure_array_colon_for_comma", b"[1:2]", "n")
case("n_structure_line_comment_after_value", b"[1] // ok", "n")
case("n_structure_block_comment_before_value", b"/*c*/[1]", "n")
case("n_structure_single_star", b"*", "n")
case("n_structure_bare_word", b"nul", "n")
case("n_structure_true_with_trailing_letters", b"truex", "n")
case("n_structure_capital_true", b"True", "n")
case("n_structure_capital_null", b"NULL", "n")

# --------------------------------------------------------------------------
# Numbers. The grammar is small and almost every parser is wider than it,
# because the languages they are written in have wider literal syntax. Every
# case below is something `str::parse::<f64>` accepts and JSON does not, or a
# magnitude that decides whether a parser rounds evidence before storing it.
# --------------------------------------------------------------------------
case("y_number_zero", b"[0]", "y")
case("y_number_negative_zero", b"[-0]", "y")
case("y_number_negative_int", b"[-123]", "y")
case("y_number_fraction_leading_zero", b"[0.5]", "y")
case("y_number_zero_exponent", b"[0e1]", "y")
case("y_number_zero_exponent_plus", b"[0e+1]", "y")
case("y_number_capital_exponent", b"[1E2]", "y")
case("y_number_exponent_leading_zero", b"[1e01]", "y")
case("y_number_zero_capital_exponent_zero", b"[0E0]", "y")
case("y_number_real_exponent", b"[1.5e3]", "y")
case("y_number_real_negative_exponent", b"[1.5e-3]", "y")
case("y_number_padded_by_whitespace", b"[ 1 ]", "y")
case("y_number_i64_max", b"[9223372036854775807]", "y")
case("y_number_i64_min", b"[-9223372036854775808]", "y")
case("y_number_u64_max", b"[18446744073709551615]", "y")
case("y_number_smallest_normal_double", b"[2.2250738585072011e-308]", "y")
case("y_number_more_precision_than_double", b"[1.000000000000000005]", "y")
case("y_number_nanosecond_timestamp", b"[1753900000123456789]", "y")

# Grammar-conformant magnitudes with no exact representation in a double, so
# what a parser hands back is the implementation's answer and not the RFC's.
case("i_number_i64_max_plus_one", b"[9223372036854775808]", "i")
case("i_number_u64_max_plus_one", b"[18446744073709551616]", "i")
case("i_number_huge_positive_exponent", b"[1e999]", "i")
case("i_number_huge_negative_exponent", b"[1e-999]", "i")
case("i_number_real_underflow", b"[123.456e-789]", "i")
case("i_number_exponent_expansion", b"[9.223372E+1010671858]", "i")
case("i_number_1024_digit_integer", b"[" + digits(1024) + b"]", "i")
case("i_number_1025_digit_integer", b"[" + digits(1025) + b"]", "i")
case("i_number_5000_digit_integer", b"[" + digits(5000) + b"]", "i")
# The same five thousand digits after a decimal point, because CPython's
# 4300-digit conversion limit applies to integers only and this is the case that
# proves a length bound has to be measured on the literal rather than inferred
# from what the host language will convert.
case("i_number_5000_digit_fraction", b"[0." + b"1" * 5000 + b"]", "i")

case("n_number_leading_zero", b"[01]", "n")
case("n_number_negative_leading_zero", b"[-01]", "n")
case("n_number_double_zero", b"[00]", "n")
case("n_number_leading_zero_with_exponent", b"[012e3]", "n")
case("n_number_leading_plus", b"[+1]", "n")
case("n_number_bare_fraction", b"[.5]", "n")
case("n_number_trailing_dot", b"[5.]", "n")
case("n_number_dot_before_exponent", b"[1.e1]", "n")
case("n_number_dot_only", b"[.]", "n")
case("n_number_minus_only", b"[-]", "n")
case("n_number_double_minus", b"[--1]", "n")
case("n_number_exponent_no_digits", b"[1e]", "n")
case("n_number_exponent_plus_no_digits", b"[1e+]", "n")
case("n_number_exponent_minus_no_digits", b"[1e-]", "n")
case("n_number_bare_exponent", b"[e1]", "n")
case("n_number_double_exponent", b"[1e1e1]", "n")
case("n_number_trailing_plus", b"[1+]", "n")
case("n_number_double_dot", b"[1..2]", "n")
case("n_number_trailing_letter", b"[1f]", "n")
case("n_number_hex_literal", b"[0x1f]", "n")
case("n_number_digit_separator", b"[1_000]", "n")
case("n_number_space_inside", b"[1 000]", "n")
case("n_number_inf", b"[Inf]", "n")
case("n_number_infinity", b"[Infinity]", "n")
case("n_number_negative_infinity", b"[-Infinity]", "n")
case("n_number_nan", b"[NaN]", "n")
case("n_number_negative_nan", b"[-NaN]", "n")
case("n_number_infinity_as_object_value", b'{"a":Infinity}', "n")

# --------------------------------------------------------------------------
# Strings. Two classes here are security-relevant rather than pedantic.
#
# A raw LF inside a string is what lets one logical record be split across two
# lines, which puts an attacker-controlled record between the halves of a real
# one. A lone surrogate is what lets `"superadmin\ud888"` become `superadmin`
# in any parser that truncates instead of refusing.
# --------------------------------------------------------------------------
case("y_string_simple", b'["asd"]', "y")
case("y_string_empty", b'[""]', "y")
case("y_string_all_simple_escapes", b'["\\"\\\\\\/\\b\\f\\n\\r\\t"]', "y")
case("y_string_escaped_nul", b'["\\u0000"]', "y")
case("y_string_escaped_unit_separator", b'["\\u001f"]', "y")
case("y_string_escaped_structure_is_not_structure", b'["\\u005b\\u0031\\u005d"]', "y")
case("y_string_escaped_comma_and_quotes", b'["a\\u002c\\u0022b\\u0022"]', "y")
case("y_string_escaped_lf_is_not_a_separator", b'["a\\nb"]', "y")
case("y_string_raw_del", b'["\x7f"]', "y")
case("y_string_raw_c1_controls", b'["\xc2\x80\xc2\x85\xc2\x9f"]', "y")
case("y_string_raw_line_separators", b'["\xe2\x80\xa8\xe2\x80\xa9"]', "y")
case("y_string_escaped_line_separators", b'["\\u2028\\u2029"]', "y")
case("y_string_noncharacter_uffff_escaped", b'["\\uffff"]', "y")
case("y_string_noncharacter_uffff_raw", b'["\xef\xbf\xbf"]', "y")
case("y_string_noncharacter_ufdd0_raw", b'["\xef\xb7\x90"]', "y")
case("y_string_replacement_char_escaped", b'["\\ufffd"]', "y")
case("y_string_valid_surrogate_pair", b'["\\ud83d\\ude00"]', "y")
case("y_string_last_scalar_value_escaped", b'["\\udbff\\udfff"]', "y")
case("y_string_last_scalar_value_raw", b'["\xf4\x8f\xbf\xbf"]', "y")
case("y_string_utf8_two_three_four_byte", b'["\xc2\xa3\xe2\x82\xac\xf0\x9d\x84\x9e"]', "y")
case("y_string_escaped_quote_inside", b'["a\\"b"]', "y")
case("y_string_trailing_escaped_backslash", b'["a\\\\"]', "y")
case("y_string_solidus_raw_and_escaped", b'["/\\/"]', "y")
case("y_string_escaped_key_and_value", b'{"\\u006b":"\\u0076"}', "y")

# A lone surrogate is grammar-conformant text, so the RFC verdict is `i`: what a
# parser does with it is the parser's answer, and the answers include U+FFFD
# substitution, truncation and refusal.
case("i_string_lone_high_surrogate_escaped", b'["\\ud800"]', "i")
case("i_string_lone_low_surrogate_escaped", b'["\\udc00"]', "i")
case("i_string_high_surrogate_then_bmp", b'["\\ud888\\u1234"]', "i")
case("i_string_two_high_surrogates", b'["\\ud834\\ud834"]', "i")
case("i_string_low_then_high_surrogate", b'["\\udc00\\ud800"]', "i")
case("i_string_high_surrogate_after_text", b'["superadmin\\ud888"]', "i")
case("i_string_lone_surrogate_as_key", b'{"\\ud800":1}', "i")

case("n_string_single_quotes", b"['a']", "n")
case("n_string_unterminated", b'["abc]', "n")
case("n_string_escape_then_eof", b'["a\\', "n")
case("n_string_backslash_before_closing_quote", b'["\\"]', "n")
case("n_string_bad_escape_apostrophe", b'["\\\'"]', "n")
case("n_string_bad_escape_x", b'["\\x41"]', "n")
case("n_string_bad_escape_zero", b'["\\0"]', "n")
case("n_string_bad_escape_capital_u", b'["\\U0041"]', "n")
case("n_string_bad_escape_a", b'["\\a"]', "n")
case("n_string_bad_escape_v", b'["\\v"]', "n")
case("n_string_bad_escape_line_continuation", b'["a\\\nb"]', "n")
case("n_string_short_u_escape", b'["\\u00"]', "n")
case("n_string_nonhex_u_escape", b'["\\uZZZZ"]', "n")
case("n_string_u_escape_with_space", b'["\\u00 1"]', "n")
case("n_string_u_escape_with_brace", b'["\\u{41}"]', "n")
case("n_string_u_escape_truncated_by_quote", b'["\\u1"]', "n")
case("n_string_raw_tab", b'["\t"]', "n")
case("n_string_raw_lf", b'["\n"]', "n")
case("n_string_raw_cr", b'["\r"]', "n")
case("n_string_raw_nul", b'["\x00"]', "n")
case("n_string_raw_unit_separator", b'["\x1f"]', "n")
case("n_string_raw_backspace", b'["\x08"]', "n")
case("n_string_raw_form_feed", b'["\x0c"]', "n")
case("n_string_raw_lf_in_key", b'{"a\nb":1}', "n")

# --------------------------------------------------------------------------
# Encoding. A parser that repairs invalid UTF-8 with U+FFFD changes the bytes
# an audit store hashes, so every case here has to come back as an encoding
# refusal and not as a document with different content.
#
# The byte-order-mark cases are here rather than in structure because a BOM is a
# claim about the encoding of the whole stream, and the wrong answer is to read
# UTF-16 as ASCII: the interleaved NULs make it look like a truncated ASCII
# document instead of the wrong encoding.
# --------------------------------------------------------------------------
case("n_encoding_overlong_slash_c0_af", b'["\xc0\xaf"]', "n")
case("n_encoding_overlong_nul_c0_80", b'["\xc0\x80"]', "n")
case("n_encoding_overlong_three_byte", b'["\xe0\x80\xaf"]', "n")
case("n_encoding_surrogate_ed_a0_80", b'["\xed\xa0\x80"]', "n")
case("n_encoding_surrogate_pair_raw_utf8", b'["\xed\xa0\xbd\xed\xb8\x80"]', "n")
case("n_encoding_above_max_f4_bf_bf_bf", b'["\xf4\xbf\xbf\xbf"]', "n")
case("n_encoding_five_byte_start_f8", b'["\xf8\x88\x80\x80\x80"]', "n")
case("n_encoding_lone_continuation_byte", b'["\x80"]', "n")
case("n_encoding_truncated_three_byte", b'["\xe2\x82"]', "n")
case("n_encoding_fe_byte", b'["\xfe"]', "n")
case("n_encoding_invalid_in_number", b"[1\xff2]", "n")
case("n_encoding_invalid_in_exponent", b"[1e\xff1]", "n")
case("n_encoding_invalid_in_escape", b'["\\\xff"]', "n")
case("n_encoding_invalid_in_key", b'{"\xff":1}', "n")
case("n_encoding_invalid_before_value", b"\xff[1]", "n")
case("n_encoding_invalid_after_value", b"[1]\xff", "n")
case("i_encoding_utf8_bom_then_object", b'\xef\xbb\xbf{"a":1}', "i")
case("i_encoding_utf8_bom_then_scalar", b"\xef\xbb\xbf1", "i")
case("n_encoding_utf8_bom_only", b"\xef\xbb\xbf", "n")
case("n_encoding_utf8_bom_inside_array", b"[\xef\xbb\xbf1]", "n")
case("n_encoding_utf8_bom_before_key", b'{\xef\xbb\xbf"a":1}', "n")
case(
    "n_encoding_utf16le_bom",
    b"\xff\xfe{\x00\"\x00a\x00\"\x00:\x001\x00}\x00",
    "n",
)
case(
    "n_encoding_utf16be_bom",
    b"\xfe\xff\x00{\x00\"\x00a\x00\"\x00:\x001\x00}",
    "n",
)
case(
    "n_encoding_utf32le_bom",
    b"\xff\xfe\x00\x00[\x00\x00\x001\x00\x00\x00]\x00\x00\x00",
    "n",
)
case(
    "n_encoding_utf32be_bom",
    b"\x00\x00\xfe\xff\x00\x00\x00[\x00\x00\x001\x00\x00\x00]",
    "n",
)
case("n_encoding_utf16le_no_bom", b'{\x00"\x00a\x00"\x00:\x001\x00}\x00', "n")
case("n_encoding_utf16be_no_bom", b'\x00{\x00"\x00a\x00"\x00:\x001\x00}', "n")

# --------------------------------------------------------------------------
# Whitespace. RFC 8259 allows exactly four bytes between tokens: space, tab, LF
# and CR. Both of the obvious library predicates are wrong, which is why these
# cases exist: `is_ascii_whitespace` adds form feed, and `char::is_whitespace`
# adds U+00A0 and U+2028.
# --------------------------------------------------------------------------
case("y_whitespace_all_four_around_value", b"\t\r\n [ 1 ]\t\r\n ", "y")
case("y_whitespace_lone_cr_between_elements", b"[1,\r2]", "y")
case("y_whitespace_newlines_inside_object", b'{\n"a"\n:\n1\n}', "y")
case("y_whitespace_flood_before_value", b" " * 10000 + b"[1]", "y")
case("y_whitespace_flood_inside_array", b"[" + b" " * 10000 + b"1]", "y")
case("y_whitespace_flood_between_members", b'{"a"' + b" " * 10000 + b":1}", "y")
case("n_whitespace_form_feed_separator", b"[1,\x0c2]", "n")
case("n_whitespace_form_feed_leading", b"\x0c[1]", "n")
case("n_whitespace_vertical_tab_separator", b"[1,\x0b2]", "n")
case("n_whitespace_nbsp_before_value", b"[\xc2\xa01]", "n")
case("n_whitespace_line_separator_between_elements", b"[1,\xe2\x80\xa82]", "n")
case("n_whitespace_ideographic_space", b"[\xe3\x80\x801]", "n")
case("n_whitespace_cr_between_two_values", b"[1]\r[2]", "n")

# --------------------------------------------------------------------------
# Duplicate member names. RFC 8259 contradicts itself here (section 4 blesses
# reporting an error, section 9 says accept every grammar-conformant text), so
# the verdict below is `y` and the divergence is ours to declare. CVE-2017-12635
# is what the last-wins answer looks like from the outside.
#
# The normalisation pair is the case that stops a well-meaning fix: an NFC and
# an NFD spelling of the same word are two different keys, and a parser that
# folded them would be making a linguistic decision about evidence.
# --------------------------------------------------------------------------
case("y_object_duplicate_key", b'{"a":1,"a":2}', "y")
case("y_object_duplicate_key_same_value", b'{"a":1,"a":1}', "y")
case("y_object_duplicate_key_escaped_name", b'{"a":1,"\\u0061":2}', "y")
case("y_object_duplicate_key_escaped_backslash", b'{"a\\\\b":1,"a\\u005cb":2}', "y")
case("y_object_duplicate_empty_key", b'{"":1,"":2}', "y")
case("y_object_duplicate_key_after_nested", b'{"a":{"b":1},"a":2}', "y")
case("y_object_duplicate_key_inside_array", b'[{"a":1,"a":2}]', "y")
case("y_object_nfc_and_nfd_keys", b'{"\xc3\xa9":1,"e\xcc\x81":2}', "y")
case("y_object_same_name_in_sibling_objects", b'{"a":{"b":1},"c":{"b":2}}', "y")
case("y_object_keys_differ_by_case", b'{"a":1,"A":2}', "y")


def main() -> None:
    seen: set[str] = set()
    out = sys.stdout
    for name, raw, verdict in CASES:
        # A duplicated name would not be a cosmetic problem. Every consumer of
        # this corpus keys on the name, so the second copy would replace the
        # first and the corpus would quietly be one case smaller than it says.
        if name in seen:
            raise SystemExit(f"duplicate case name: {name}")
        seen.add(name)
        if verdict not in ("y", "n", "i"):
            raise SystemExit(f"{name}: verdict must be y, n or i, not {verdict!r}")
        if not name.startswith(verdict + "_"):
            raise SystemExit(f"{name}: name prefix disagrees with verdict {verdict!r}")
        out.write(f"{name}\t{raw.hex()}\t{verdict}\n")


if __name__ == "__main__":
    main()
