//! The one date format a signature needs, and an oracle for it.
//!
//! SigV4 dates every request as `YYYYMMDDTHHMMSSZ` in UTC, and the first eight
//! characters of that string are also the scope's date. Get the civil arithmetic
//! wrong and every request fails with `SignatureDoesNotMatch`, on the days it is
//! wrong, which for a naive month table is the days after a leap year.
//!
//! The conversion is Howard Hinnant's `civil_from_days`, the inverse of the
//! `days_from_civil` the ASN.1 reader already uses for RFC 3161 times, so both
//! directions in this workspace come from the same worked-out algorithm rather than
//! from two people's month tables. It is exact for every date in range, including
//! the century rules that make 2000 a leap year and 2100 not one.
//!
//! The test asserts against a table generated by Python's `datetime`, which is the
//! same doctrine used for the timestamp tokens: an implementation checked only
//! against itself is an implementation whose bugs are consistent.

/// `YYYYMMDDTHHMMSSZ` for an instant given in seconds since the epoch.
pub fn amz_timestamp(unix_seconds: u64) -> String {
    let days = (unix_seconds / 86_400) as i64;
    let rest = unix_seconds % 86_400;
    let (year, month, day) = civil_from_days(days);
    let (hour, minute, second) = (rest / 3600, (rest % 3600) / 60, rest % 60);
    format!("{year:04}{month:02}{day:02}T{hour:02}{minute:02}{second:02}Z")
}

/// Howard Hinnant's `civil_from_days`: days since 1970-01-01 to a civil date.
///
/// The era arithmetic is what makes the century rules fall out rather than being
/// special-cased, which is why this is copied rather than reinvented.
fn civil_from_days(days: i64) -> (i64, i64, i64) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let day_of_era = z - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let mp = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * mp + 2) / 5 + 1;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    (if month <= 2 { year + 1 } else { year }, month, day)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generated by Python's `datetime`, which is a second implementation by other
    /// people. The interesting rows are 2000-02-29 (a leap year by the 400 rule),
    /// 2100-03-01 (not a leap year by the 100 rule), both sides of a year boundary,
    /// and the 2038 second that overflows a 32-bit time.
    #[test]
    fn every_timestamp_matches_an_independent_implementation() {
        for (seconds, expected) in [
            (0, "19700101T000000Z"),
            (1, "19700101T000001Z"),
            (145_465_423, "19740811T150343Z"),
            (254_944_917, "19780129T180157Z"),
            (280_571_490, "19781122T083130Z"),
            (295_963_137, "19790519T115857Z"),
            (305_421_701, "19790905T232141Z"),
            (724_612_665, "19921217T171745Z"),
            (739_868_484, "19930612T070124Z"),
            (750_898_254, "19931017T225054Z"),
            (844_652_667, "19961007T014427Z"),
            (951_782_400, "20000229T000000Z"),
            (951_868_800, "20000301T000000Z"),
            (972_406_844, "20001024T170044Z"),
            (1_050_238_895, "20030413T130135Z"),
            (1_061_937_468, "20030826T223748Z"),
            (1_091_910_880, "20040807T203440Z"),
            (1_199_894_415, "20080109T160015Z"),
            (1_266_926_147, "20100223T115547Z"),
            (1_417_613_921, "20141203T133841Z"),
            (1_528_474_670, "20180608T161750Z"),
            (1_544_527_643, "20181211T112723Z"),
            (1_714_377_209, "20240429T075329Z"),
            (1_732_368_646, "20241123T133046Z"),
            (1_767_225_599, "20251231T235959Z"),
            (1_767_225_600, "20260101T000000Z"),
            (1_772_323_200, "20260301T000000Z"),
            (2_009_913_091, "20330909T211131Z"),
            (2_147_483_647, "20380119T031407Z"),
            (2_150_966_716, "20380228T104516Z"),
            (2_225_589_129, "20400711T031209Z"),
            (2_292_640_455, "20420826T043415Z"),
            (2_316_339_984, "20430527T114624Z"),
            (2_415_172_659, "20460714T091739Z"),
            (2_416_177_447, "20460726T002407Z"),
            (2_448_342_902, "20470802T071502Z"),
            (2_543_452_143, "20500807T022903Z"),
            (2_545_938_666, "20500904T211106Z"),
            (2_568_013_262, "20510518T090102Z"),
            (2_982_464_414, "20640705T062014Z"),
            (3_006_382_083, "20650408T020803Z"),
            (3_034_447_070, "20660226T215750Z"),
            (3_151_258_907, "20691109T214147Z"),
            (3_249_824_204, "20721224T165644Z"),
            (3_288_372_379, "20740315T204619Z"),
            (3_507_441_901, "20810222T092501Z"),
            (4_073_141_809, "20990126T201649Z"),
            (4_099_366_197, "20991126T084957Z"),
            (4_107_542_400, "21000301T000000Z"),
            (253_402_300_799, "99991231T235959Z"),
        ] {
            assert_eq!(amz_timestamp(seconds), expected, "at {seconds}");
        }
    }

    /// The scope's date is the first eight characters, so a timestamp that is one
    /// character out of shape produces a scope nobody can match.
    #[test]
    fn the_first_eight_characters_are_the_scope_date() {
        let stamp = amz_timestamp(1_772_323_200);
        assert_eq!(&stamp[..8], "20260301");
        assert_eq!(stamp.len(), 16);
        assert!(stamp.ends_with('Z') && stamp.as_bytes()[8] == b'T');
    }
}
